[main]
nats_server_url = "http://user:secret@localhost:4222"
encryption_key  = "super-secret-key"
nats_stream    = "HASHUP"
nats_subject   = "FILES"

[store]
stats_interval = 30
#db_path       = # defaults to ~/.local/share/hashup

[indexer]
indexing_interval     = 3600
indexing_concurrency  = 5
