[main]
nats_server_url = "http://user:secret@localhost:4222"
encryption_key  = "super-secret-key"
nats_stream    = "HASHUP"
nats_subject   = "FILES"

[store]
stats_interval = 15
#db_path       = # defaults to ~/.local/share/hashup

[scanner]
scanning_interval     = 3600
scanning_concurrency  = 5
